package qiwi.util.enums;

public enum TypeAndLanguage {
    TO_READ_ENGLISH, TO_READ_RUSSIAN, TO_READ_SPANISH,
    FINISHED_ENGLISH, FINISHED_RUSSIAN, FINISHED_SPANISH,
    DATES_ENGLISH, DATES_RUSSIAN, DATES_SPANISH
}
